apiVersion: v1
kind: Service
metadata:
  name: release-name-matrix-service
  labels:
    helm.sh/chart: matrix-service-0.1.0
    app.kubernetes.io/name: matrix-service
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: matrix-service
    app.kubernetes.io/instance: release-name