# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN go build -o app

# Run stage
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/app .

COPY --from=builder /app/static ./static

EXPOSE 8080

CMD ["./app"]